### ISSUE TITLE
Esto no es trampa ? no se supone que deba de aparecer los detalles de cada producto seleccionado cuando se le de click, en lugar de siempre aparecer "Leaf Rake" en los detalles?

### ISSUE THREAD

**Issue by mariobustosjmz** [RicardoRdz96/ExerciseDanielRdz#2]
https://github.com/RicardoRdz96/ExerciseDanielRdz/blob/8a02fe40004e271bc2720d1afa5b7c59df55665d/Exercises/ExerciseVideosRicardo/src/app/products/product-detail.component.ts#L20

**Comment by RicardoRdz96** [comment]
**Dentro del product-list component que es la vista, y el ts y product-detail.ts** si en dado caso en esta parte requiere buscar o si tu editas la URL de http y colocas ejemplo prodcuts/**cocacola**, no aparecera, si en este caso colocas el id asignado al producto, aparecera de este modo, cuando me voy a la pantalla , le doi click al dicho producto , pues me arroja a otra ventana, donde pueda a ver una descripción, pero como no lo hay y **solo es un filtrado de producto, pues no coloque información adicional en cada producto, si en dado caso se requiera lo agrego, mas no me lo menciona en el vídeo**

**Comment by mariobustosjmz** [comment]
me parece rao que el curso no muestre una pantalla de detalles ( a menos que con lo ilustrado en los ejercicios el curso esperana que ustedes lo terminaran)

sea como sea, siento necesario agregarlo, practicamente es lo mismo.
cuando selecciones un producto valido y vayas al componente de detalles, en este se debera de mostrar todos los detalles que tenga ese id product en especifico.

```
"productId": 2,
    "productName": "Garden Cart",
    "productCode": "GDN-0023",
    "releaseDate": "March 18, 2016",
    "description": "15 gallon capacity rolling garden cart",
    "price": 32.99,
    "starRating": 4.2,
    "imageUrl": "https://openclipart.org/image/300px/svg_to_png/58471/garden_cart.png"
```
por lo que veo sera necesario agregar un metodo getProductDetail en el servicio, que tome el id como parametro y dentro del pipe haga el filtro para solo devolverte un resultado, esto seria mandaria a llamar  en el product detail para poder usarse en el template , es lo mismo que getproducts ,lo nuevo seria como filtrar por id pero en ese caso podria ayudarles.
